
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Compiladores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 9;
  public static final int DIFERENCIA = 20;
  public static final int CHAR = 42;
  public static final int CONST = 39;
  public static final int GUIONBAJO = 37;
  public static final int POR = 16;
  public static final int PUNTOYCOMA = 10;
  public static final int ENTERO = 2;
  public static final int XOR = 27;
  public static final int DOUBLE = 46;
  public static final int CONTINUE = 51;
  public static final int INT = 40;
  public static final int CORCHETE_C = 36;
  public static final int PRINTLN = 45;
  public static final int CORCHETE_A = 35;
  public static final int LLAVE_C = 34;
  public static final int FOR = 49;
  public static final int LLAVE_A = 33;
  public static final int MATCH = 48;
  public static final int NOT = 28;
  public static final int MENORIGUAL = 22;
  public static final int AND = 26;
  public static final int IGUAL = 12;
  public static final int CARACTER = 8;
  public static final int OR = 25;
  public static final int SUMA = 14;
  public static final int UMENOS = 54;
  public static final int IF = 44;
  public static final int ID = 4;
  public static final int MAYORIGUAL = 24;
  public static final int EOF = 0;
  public static final int DECIMAL = 3;
  public static final int STARTWITH = 53;
  public static final int TRUE = 6;
  public static final int error = 1;
  public static final int COMA = 11;
  public static final int CADENA = 5;
  public static final int MENOS = 15;
  public static final int MENOR = 21;
  public static final int MOD = 19;
  public static final int BREAK = 50;
  public static final int VOID = 52;
  public static final int DOSIGUAL = 13;
  public static final int MAYOR = 23;
  public static final int POTENCIA = 18;
  public static final int ELSE = 47;
  public static final int PARENTESIS_C = 32;
  public static final int WHILE = 30;
  public static final int PARENTESIS_A = 31;
  public static final int BOOLEANO = 41;
  public static final int STRING = 43;
  public static final int FALSE = 7;
  public static final int DIVISION = 17;
  public static final int VAR = 38;
  public static final int DO = 29;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ENTERO",
  "DECIMAL",
  "ID",
  "CADENA",
  "TRUE",
  "FALSE",
  "CARACTER",
  "DOSPUNTOS",
  "PUNTOYCOMA",
  "COMA",
  "IGUAL",
  "DOSIGUAL",
  "SUMA",
  "MENOS",
  "POR",
  "DIVISION",
  "POTENCIA",
  "MOD",
  "DIFERENCIA",
  "MENOR",
  "MENORIGUAL",
  "MAYOR",
  "MAYORIGUAL",
  "OR",
  "AND",
  "XOR",
  "NOT",
  "DO",
  "WHILE",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "LLAVE_A",
  "LLAVE_C",
  "CORCHETE_A",
  "CORCHETE_C",
  "GUIONBAJO",
  "VAR",
  "CONST",
  "INT",
  "BOOLEANO",
  "CHAR",
  "STRING",
  "IF",
  "PRINTLN",
  "DOUBLE",
  "ELSE",
  "MATCH",
  "FOR",
  "BREAK",
  "CONTINUE",
  "VOID",
  "STARTWITH",
  "UMENOS"
  };
}

