
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Compiladores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 5;
  public static final int DIFERENCIA = 15;
  public static final int CONST = 31;
  public static final int POR = 11;
  public static final int CHAR = 34;
  public static final int PUNTOYCOMA = 6;
  public static final int ENTERO = 2;
  public static final int XOR = 22;
  public static final int CORCHETE_C = 29;
  public static final int INT = 32;
  public static final int PRINTLN = 37;
  public static final int CORCHETE_A = 28;
  public static final int LLAVE_C = 27;
  public static final int LLAVE_A = 26;
  public static final int NOT = 23;
  public static final int MENORIGUAL = 17;
  public static final int AND = 21;
  public static final int IGUAL = 7;
  public static final int OR = 20;
  public static final int SUMA = 9;
  public static final int UMENOS = 38;
  public static final int IF = 36;
  public static final int ID = 4;
  public static final int MAYORIGUAL = 19;
  public static final int EOF = 0;
  public static final int DECIMAL = 3;
  public static final int error = 1;
  public static final int MENOS = 10;
  public static final int MENOR = 16;
  public static final int MOD = 14;
  public static final int DOSIGUAL = 8;
  public static final int MAYOR = 18;
  public static final int POTENCIA = 13;
  public static final int PARENTESIS_C = 25;
  public static final int PARENTESIS_A = 24;
  public static final int BOOLEANO = 33;
  public static final int STRING = 35;
  public static final int DIVISION = 12;
  public static final int VAR = 30;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ENTERO",
  "DECIMAL",
  "ID",
  "DOSPUNTOS",
  "PUNTOYCOMA",
  "IGUAL",
  "DOSIGUAL",
  "SUMA",
  "MENOS",
  "POR",
  "DIVISION",
  "POTENCIA",
  "MOD",
  "DIFERENCIA",
  "MENOR",
  "MENORIGUAL",
  "MAYOR",
  "MAYORIGUAL",
  "OR",
  "AND",
  "XOR",
  "NOT",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "LLAVE_A",
  "LLAVE_C",
  "CORCHETE_A",
  "CORCHETE_C",
  "VAR",
  "CONST",
  "INT",
  "BOOLEANO",
  "CHAR",
  "STRING",
  "IF",
  "PRINTLN",
  "UMENOS"
  };
}

